version: '3'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: postgres_db
    depends_on:
      postgres_db:
        condition: service_healthy
  postgres_db:
    image: "postgres:13"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abcd1234
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 2s